INSERT INTO exercises (eq_id, mg_id, ex_name)
VALUES
-- Chest exercises
(1, 1, 'Bench Press'),
(1, 1, 'Inclined Bench Press'),
(1, 1, 'Decline Bench Press'),
(2, 1, 'Dumbbell Chest Press'),
(2, 1, 'Dumbbell Fly'),
(4, 1, 'Chest Dips'),
(4, 1, 'Push-Ups'),
(3, 1, 'Cable Crossover'),
(2, 1, 'Inclined Dumbbell Press'),
(2, 1, 'Inclined Fly'),
(3, 1, 'Pec Deck Machine'),
(4, 1, 'Plyometric Push-Ups'),
(4, 1, 'Wide Grip Push-Ups'),
(2, 1, 'Dumbell Pullovers')

-- Back exercises
(1, 2, 'Barbell Rows'),
(1, 2, 'T-Bar Rows'),
(1, 2, 'Bent Over Rows'),
(2, 2, 'One-Arm Dumbbell Rows'),
(3, 2, 'Seated Cable Rows'),
(4, 2, 'Chin-Ups'),
(4, 2, 'Pull-Ups'),
(2, 2, 'Dumbbell Rows'),
(2, 2, 'Renegade Rows'),
(2, 2, 'Bent Over Reverse Fly'),
(3, 2, 'Wide Grip Lat Pulldowns'),
(3, 2, 'Close Grip Lat Pulldowns'),
(3, 2, 'Lat Pulldowns'),
(3, 2, 'Machine Pullovers'),
(3, 2, 'Straight Arm Pulldowns'),
(3, 2, 'Assisted Pull-Ups'),

-- Legs exercises
(1, 3, 'Squats'),
(1, 3, 'Front Squats'),
(3, 3, 'Hack Squats'),
(3, 3, 'Leg Press'),
(2, 3, 'Barbell Lunges'),
(2, 3, 'Step-Ups'),
(2, 3, 'Dumbbell Lunges'),
(2, 3, 'Goblet Squats'),
(2, 3, 'Bulgarian Split Squats'),
(3, 3, 'Leg Extensions'),
(3, 3, 'Hamstring Curls'),
(3, 3, 'Seated Leg Curl'),
(3, 3, 'Leg Adduction Machine'),

-- Triceps exercises
(1, 4, 'Close Grip Bench Press'),
(1, 4, 'Skull Crushers'),
(4, 4, 'Triceps Dips'),
(1, 4, 'Overhead Triceps Extension'),
(3, 4, 'Cable Pushdowns'),
(4, 4, 'Diamond Push-Ups'),
(2, 4, 'Dumbbell Triceps Extension'),
(2, 4, 'Seated Triceps Press'),
(2, 4, 'Triceps Kickbacks'),
(2, 4, 'Dumbbell Skull Crushers'),
(3, 4, 'Cable Rope Overhead Triceps Extension'),
(3, 4, 'Triceps Pushdowns'),
(3, 4, 'Triceps Rope Pushdowns'),
(3, 4, 'Dip Machine'),
(3, 4, 'V-Bar Pushdowns'),

-- Biceps exercises
(2, 5, 'Barbell Curls'),
(2, 5, 'Hammer Curls'),
(1, 5, 'Preacher Curls'),
(2, 5, 'Incline Dumbbell Curls'),
(2, 5, 'Concentration Curls'),
(4, 5, 'Chin-Ups'),
(2, 5, 'Dumbbell Hammer Curls'),
(2, 5, 'Spider Curls'),
(1, 5, 'EZ Bar Curls'),
(3, 5, 'Cable Curls'),
(2, 5, 'Reverse Grip Barbell Curls'),
(3, 5, 'Cable Preacher Curls'),
(3, 5, 'Machine Bicep Curls'),
(3, 5, 'Reverse Cable Curls'),

-- Shoulders exercises
(1, 6, 'Military Press'),
(2, 6, 'Arnold Press'),
(1, 6, 'Push Press'),
(2, 6, 'Barbell Front Raise'),
(2, 6, 'Barbell Upright Row'),
(2, 6, 'Lateral Raises'),
(1, 6, 'Barbell Shrugs'),
(2, 6, 'Dumbbell Shoulder Press'),
(2, 6, 'Bent-Over Dumbbell Reverse Fly'),
(2, 6, 'Dumbbell Shrug'),
(3, 6, 'Machine Shoulder Press'),
(3, 6, 'Cable Lateral Raises'),
(3, 6, 'Cable Face Pulls'),

-- Abs exercises
(4, 7, 'Crunches'),
(4, 7, 'Russian Twists'),
(4, 7, 'Leg Raises'),
(4, 7, 'Plank'),
(5, 7, 'Machine Crunches'),
(5, 7, 'Cable Woodchoppers'),
(5, 7, 'Decline Sit-Ups'),

-- Calves exercises
(3, 8, 'Standing Calf Raises'),
(3, 8, 'Seated Calf Raises'),
(5, 8, 'Machine Calf Raises'),
(5, 8, 'Donkey Calf Raises'),
(4, 8, 'Calf Raises'),

-- Forearms exercises
(2, 9, 'Reverse Barbell Curls'),
(2, 9, 'Wrist Curls'),
(2, 9, 'Farmers Walk'),
(2, 9, 'Dumbbell Wrist Curls'),
(2, 9, 'Reverse Dumbbell Wrist Curls'),
(4, 9, 'Reverse Push-Ups'),
(4, 9, 'Finger Push-Ups');
